apiVersion: v1
kind: Pod
metadata:
  name: posix-pod
  labels:
    name: posix
spec:
  containers:
  - name: posix
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080
    envFrom:
      - configMapRef: 
        name: posix-configmap
          