apiVersion: v1
kind: Pod
metadata:
  name: mypod-volumesecret
spec:
  containers:
  - name: myapp
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
  volumes:
  - name: foo
    secret: 
      secretName: vprofile-secret

