apiVersion: v1
kind: Pod
metadata:
  name: liveness-html
  labels:
    test: livenesshtml
spec:
  containers:
  - name: livenesshtml
    image: k8s.gcr.io/liveness
    resources:
        limits:
          memory: "128Mi"
          cpu: "100m"
    args:
      - /server
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: custome-header
          value: Awesome        
      initialDelaySeconds: 5
      periodSeconds: 5
