apiVersion: v1
kind: Pod
metadata:
  name: mysql-db-pod
  labels:
    name: mysql-db
spec:
  containers:
  - name: mysql-db
    image: mysql:5.7
    ports:
      - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: rootpassword
      - name: MYSQL_USER
        value: root
      - name: MYSQL_PASSWORD
        value: rootpassword
      - name: MYSQL_DATABASE
        value: helloworld
