apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeselector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeselector
  template:
    metadata:
      labels:
        app: nodeselector
    spec:
      containers:
      - name: nodeselector
        image: nginx
        resources:
          limits:
            memory: "32Mi"
            cpu: "10m"
        ports:
          - name: nginxport
            containerPort: 80
      nodeSelector:
        disktype : ssd