apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-demo
spec:
  containers:
  - name: lifecycle-demo-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    lifecycle:
      postStart:
        exec:
          command: ["bin/sh", "-c", "echo Hellow from the postStart licecycle hook > /usr/share/message"]
      preStop:
        exec:
          command: ["bin/sh", "-c", "nginx -s quit" , while killall -0 nginx; do sleep 1; done"]


