apiVersion: v1
kind: ReplicationController
metadata:
  name: sameple_replication_controller
spec:
  replicas: 3
  selector:
    app: sameple_replication_controller
  template:
    metadata:
      name: sameple_replication_controller
      labels:
        app: sameple_replication_controller
    spec:
      containers:
        - name: sameple_replication_controller
          image: nbmk1981/sample-html
          ports:
            - containerPort: 80
