apiVersion: v1
kind: ReplicationController
metadata:
  name: samplerc
spec:
  replicas: 3
  selector:
    app: samplerc
  template:
    metadata:
      name: samplerc
      labels:
        app: samplerc
    spec:
      containers:
        - name: samplerc
          image: nbmk1981/sample-html
          ports:
            - containerPort: 80
