apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: vprofile/vprofiledb:v1
        volumeMounts:
        - name:  vprodb-data-vol
          mountPath: /mnt/volume_nyc3_01
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
      env:
        - name:  MYSQL_ROOT_PASSWORD  
          valueFrom:
            secretKeyRef:
              name:  vprofile-secret
              key:  db_pass